import streamlit as st


def render_disclaimer():

    st.markdown("---")

    col1, col2 = st.columns([4, 1])

    with col1:

        st.markdown("### Medical Disclaimer")

        st.warning(
            """
            This system has been developed for educational and research purposes only.

            The prediction generated by this dashboard should not be considered a
            medical diagnosis and must not replace professional medical advice,
            diagnosis, or treatment.

            Always consult a qualified healthcare professional regarding any
            medical concerns.
            """
        )

    with col2:

        st.image(
            "dashboard/assets/images/Benita.png", width=140
        )